### ISSUE TITLE
Make the readme more welcoming for new users

### ISSUE THREAD

**Issue by danielo515** [green-labs/ppx_spice#19]
Hello, thanks for this ppx.
As a newcomer to the rescript and ocaml world I don't have much experience with certain libraries, Decco is one of them. The readme of this library starts with a sentence that it's hard to understand if you don't have any decco experience:

> But, there's a restriction to parse the JSON string into a (polymorphic) variant with the Decco. The JSON data should be formed in an array. It is obvious at some point. But generally, we face the string data which needs to be parsed into the variant in most use cases.

Maybe putting some basic examples of how it looks to encode polymorphic variants with both libraries will help clarify things for newbies.

**Comment by mattdamon108** [comment]
Hi, thank your for suggestion. Good idea. I’ll make some example for newcommers.

Before that, if you need any help, let me know.

**Comment by mununki** [comment]
@danielo515 Sorry for being late. I've added some basic examples for newcomers. How does it look?

**Comment by mununki** [comment]
https://github.com/green-labs/ppx_spice/blob/main/docs/GUIDE.md

**Comment by danielo515** [comment]
Those look awesome. Thank you very much
