### ISSUE TITLE
spice.as encode generates Json.t instead of Json.JSONString

### ISSUE THREAD

**Issue by danielo515** [green-labs/ppx_spice#20]
Given this example from the readme:

```
@spice
type t = | @spice.as(`하나`) One | @spice.as(`second`) Two

// automatically generated
let t_encode = ...

// automatically generated
let t_decode = ...

let encoded = One->t_encode // Js.Json.JSONString(`하나`)

let decoded = Js.Json.string(`second`)->t_decode // Belt.Result.Ok(Two)
```

I was expecting to get, as it says Js.Json.JSONString as the type of the encoded value, but instead I'm getting just Js.Json.t
Is this the expected behaviour and there is an error on the readme or is an error in the compiled type?

**Comment by mattdamon108** [comment]
Oh! you're correct! I'll fix it.
