### ISSUE TITLE
GLIBC version not found when deploying on Vercel

### ISSUE THREAD

**Issue by reebalazs** [green-labs/ppx_spice#37]
Excuse me if I ask something obvious or stupid, as I don't understand GLIBC linking issues, and google is not helpful either.

I'm trying to use ppx_spice in my app. My code works locally, but I'm not able to deploy it on Vercel, I get the following error messages:

```
Command line: /vercel/path0/node_modules/@greenlabs/ppx-spice/./ppx '/tmp/ppx6ae30aSpice_Codecs.res' '/tmp/ppx22e3c2Spice_Codecs.res'
rescript: [2/6] src/rescript/Spice.ast
FAILED: src/rescript/Spice.ast
/vercel/path0/node_modules/@greenlabs/ppx-spice/./ppx: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /vercel/path0/node_modules/@greenlabs/ppx-spice/./ppx)
/vercel/path0/node_modules/@greenlabs/ppx-spice/./ppx: /lib64/libm.so.6: version `GLIBC_2.35' not found (required by /vercel/path0/node_modules/@greenlabs/ppx-spice/./ppx)
/vercel/path0/node_modules/@greenlabs/ppx-spice/./ppx: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /vercel/path0/node_modules/@greenlabs/ppx-spice/./ppx)
/vercel/path0/node_modules/@greenlabs/ppx-spice/./ppx: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /vercel/path0/node_modules/@greenlabs/ppx-spice/./ppx)
```

Previously I experienced a similar problem with other ppx's, including Decco, where the solution was to downgrade to a previous version of the package, but for obvious reasons I cannot do it here. I am guessing that this comes down to a missing dependency to a particular version of libc that the ppx is compiled together with.

Could you please help me solve this problem, or point me towards a solution? "Cannot use PPX on Vercel", "I need this particular Linux version" etc. is also an answer, but I'd be happy to find a solution or workaround, if there is one. Thank you in advance!

**Comment by mununki** [comment]
Thank you for reporting this issue. I found the same issue yesterday and fixed it. The latest version v0.1.10 works well now on Vercel.
I think I have something to improve more to make linking statically, but it works fine now.

**Comment by reebalazs** [comment]
Thank you! This works well.

Also, thank you for the great work you're doing on Spice. I'm just a user, but I'm intrigued to learn ppx :)

**Comment by mununki** [comment]
> Thank you! This works well.
> 
> Also, thank you for the great work you're doing on Spice. I'm just a user, but I'm intrigued to learn ppx :)

Welcome! Good for you!
