### ISSUE TITLE
getting  t_encode not found for Js.Date.t

### ISSUE THREAD

**Issue by maxlibin** [green-labs/ppx_spice#39]
Hi, Getting error with 

```
The value t_encode can't be found in Js.Date
```

with my type

```
@spice
type data = {
   createdAt: Js.Date.t
   ...
````

**Comment by mununki** [comment]
Hi!
spice supports only a JSON value as a default. If you want to decode or encode other type of value such as Js.Date.t, then you need a custom codec. https://github.com/green-labs/ppx_spice/blob/main/examples/src/CustomCodecs.res

Or, you can define the type of createdAt as string, then parse to Js.Date.t vice versa.

**Comment by maxlibin** [comment]
got it, thanks.
