### ISSUE TITLE
Support for the undefined field 

### ISSUE THREAD

**Issue by miloslavH** [green-labs/ppx_spice#47]
Hello, 
 in decco v1.6.0 the support for the undefined fields was introduced. Is there a plan to introduce the same support in spice? Namely 
```
let rawData = %raw("undefined")

@spice
type spiceUndefinedField = option<string>

switch rawData->spiceUndefinedField_decode {
| Ok(result) => Js.log2("RESULT SPICE: ", result)
| Error(error) => Js.log2("ERROR SPICE: ", error)
}

@decco
type deccoUndefinedField = option<string>

switch rawData->deccoUndefinedField_decode {
| Ok(result) => Js.log2("RESULT DECCO: ", result)
| Error(error) => Js.log2("ERROR DECCO: ", error)
}
```
Fails in spice with `ERROR SPICE:  {path: '', message: 'Not a string', value: undefined}`
Works in decco resulting in `RESULT DECCO:  undefined`

It would be very nice to have this, since now there is no way, that I know of, to handle easily undefined value.

**Comment by mununki** [comment]
Thank you for letting me know that decco's new feature. I didn't look into it yet, but it would not be difficult to implement, I guess.
Side note, ReScript v11 supports the unboxed variants that are the feature for this use case exactly.

**Comment by mununki** [comment]
Sorry for coming back so late.
I took a look at Decco's corresponding PR https://github.com/reasonml-labs/decco/pull/80, and it's a bit confusing, because undefined is not a JSON format in the first place. Like Spice, Decco is a JSON (de)serializer, so I think the undefined value is an error.

**Comment by miloslavH** [comment]
No problem. I understand that there is always a lot to do and this "feature" is not something important.

Regarding the undefined in JSON, you are of course right. There is nothing like undefined data type, there is only null, and it is true that you do not need to treat undefined in most of the cases, but in the edge cases it is convenient when you communicate with the not-typed JS world. I see reasons to not have this behavior, but at the same time also reasons to have it, and inclining more to the latter. The decision is up to you and I would definitely understand that you have the other opinion and keep the behavior as it is now. It is not a blocked in any way and we have gratefully migrated from decco to spice. Thank you for the great work. The better variant handling and optional record field support is great.

**Comment by mununki** [comment]
I'll close this issue, but if you run into any specific issues in the future, please let us know about them so we can discuss them further.
