### ISSUE TITLE
Unable to work in 'uncurried' mode with rescript v11-beta.2

### ISSUE THREAD

**Issue by JasoonS** [green-labs/ppx_spice#48]
The following code (as an example) throws gives an error when using this with `uncurried: true` setting (the default).
```rescript
@spice
type user = string
@spice
type specDatabases = Js.Dict.t<user>
```

Setting `"uncurried": false` in the bsconfig seems to fix the issue - but this isn't the default.

**Comment by mununki** [comment]
#49 
You can test the next version https://www.npmjs.com/package/@greenlabs/ppx-spice/v/0.1.15-rc0

**Comment by mununki** [comment]
https://www.npmjs.com/package/@greenlabs/ppx-spice/v/0.1.15

**Comment by mununki** [comment]
It works fine to me. Can you check your bsconfig.json configuration?
```
"ppx-flags": [
    [
      "../ppx",
      "-uncurried"
    ]
  ],
```
