### ISSUE TITLE
Compat the new Js.Json representation in v11

### ISSUE THREAD

**Issue by mununki** [green-labs/ppx_spice#50]
Js.Json internal representation changed to untagged variants in v11. Good to refactor to a corresponding representation.

**Comment by mununki** [comment]
#46

**Comment by DZakh** [comment]
Let me know when it happens. I'll update the https://dzakh.github.io/rescript-runtime-type-benchmarks/. After the change, I think `ppx-spice` will become 2+ times faster.

**Comment by mununki** [comment]
@DZakh I've improved it by using the untagged variant, and I'm excited to see what the benchmark results are.

**Comment by mununki** [comment]
Pre-release v0.2.0-beta.0 is it.

**Comment by DZakh** [comment]
Interesting, but there's no difference 🤔

**Comment by DZakh** [comment]
Ah, I mistook it with another bottleneck https://forum.rescript-lang.org/t/rescript-decoding-libraries-benchmark/3449/12?u=dzakh. This one only removes a few function calls, which almost doesn't affect performance.

**Comment by mununki** [comment]
> Ah, I mistook it with another bottleneck [forum.rescript-lang.org/t/rescript-decoding-libraries-benchmark/3449/12?u=dzakh](https://forum.rescript-lang.org/t/rescript-decoding-libraries-benchmark/3449/12?u=dzakh). This change only removes a few function calls, which almost doesn't affect performance.

Thanks for finding the bottleneck. I'll look into how to improve the performance regarding that part. 👍
