### ISSUE TITLE
  The variant constructor Js.Json.False can't be found.

### ISSUE THREAD

**Issue by Qumeric** [green-labs/ppx_spice#55]
This is literally the first thing I am trying to do with Rescript so I might be missing something obvious but I cannot compile anything. My project only contains:

```
@spice
type class = A | B
```

And I get
```
 We've found a bug for you!
  /home/anonymous/github/rescript-project-template/node_modules/@greenlabs/ppx-spice/src/rescript/Spice_Codecs.res:3:13-25

  1 │ let falseableEncode = (encoder, opt) =>
  2 │   switch opt {
  3 │   | None => Js.Json.False
  4 │   | Some(v) => encoder(v)
  5 │   }

  The variant constructor Js.Json.False can't be found.
  
  - If it's defined in another module or file, bring it into scope by:
    - Prefixing it with said module name: TheModule.Js.Json.False
    - Or specifying its type: let theValue: TheModule.theType = Js.Json.False
  - Constructors and modules are both capitalized. Did you want the latter?
    Then instead of let foo = Bar, try module Foo = Bar.
```

I have ReScript 10.1.4 and I clonned https://github.com/rescript-lang/rescript-project-template which worked fine without spice.

**Comment by Qumeric** [comment]
Seems to work with ReScript 11 though

**Comment by mununki** [comment]
I should have written something clearer about the installation, but I didn't, so there seems to be some confusion. Sorry, v10 should be using the ppx-spice@v0.1.15

**Comment by mununki** [comment]
* compiler v11 : v0.2.0
* compiler v10 : v0.1.15

**Comment by mvaled** [comment]
It compiles with 0.2.1-rc2.

**Comment by mununki** [comment]
Yes, it will be find with rc-2.
I'll release it as stable soon.
