### ISSUE TITLE
Support null

### ISSUE THREAD

**Issue by mununki** [green-labs/ppx_spice#79]
Js.Json.null, Js.null, ...

**Comment by youngkidwarrior** [comment]
Any progress on this?

**Comment by mununki** [comment]
> Any progress on this?

Didn't seize much time for this yet. I'll definitely take this down soon.

**Comment by youngkidwarrior** [comment]
No rush. I implemented a workaround for now. I'd do it myself, but ocaml is foreign to me

**Comment by mununki** [comment]
Resolved by #80
